"""init

Revision ID: 0001
Revises: 
Create Date: 2026-07-11 17:18:00.785018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('streamer_id', sa.UUID(), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['streamer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('streamer_id', 'follower_id')
    )
    op.create_index(op.f('ix_followers_created_at'), 'followers', ['created_at'], unique=False)
    op.create_index(op.f('ix_followers_follower_id'), 'followers', ['follower_id'], unique=False)
    op.create_index(op.f('ix_followers_streamer_id'), 'followers', ['streamer_id'], unique=False)
    op.create_table('streams',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('stream_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OFFLINE', 'LIVE', 'ENDED', name='status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('streamer_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['streamer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stream_key')
    )
    op.create_index(op.f('ix_streams_created_at'), 'streams', ['created_at'], unique=False)
    op.create_table('clips',
    sa.Column('stream_id', sa.UUID(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clips_created_at'), 'clips', ['created_at'], unique=False)
    op.create_index(op.f('ix_clips_creator_id'), 'clips', ['creator_id'], unique=False)
    op.create_index(op.f('ix_clips_stream_id'), 'clips', ['stream_id'], unique=False)
    op.create_table('donations',
    sa.Column('stream_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_created_at'), 'donations', ['created_at'], unique=False)
    op.create_index(op.f('ix_donations_sender_id'), 'donations', ['sender_id'], unique=False)
    op.create_index(op.f('ix_donations_stream_id'), 'donations', ['stream_id'], unique=False)
    op.create_table('stream_categories',
    sa.Column('stream_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], )
    )
    op.create_table('stream_messages',
    sa.Column('stream_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_messages_created_at'), 'stream_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_stream_messages_sender_id'), 'stream_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_stream_messages_stream_id'), 'stream_messages', ['stream_id'], unique=False)
    op.create_table('stream_metrics',
    sa.Column('stream_id', sa.UUID(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('total_donations', sa.Integer(), nullable=False),
    sa.Column('donation_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('peak_viewers', sa.Integer(), nullable=False),
    sa.Column('avg_watch_time', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_metrics_created_at'), 'stream_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_stream_metrics_stream_id'), 'stream_metrics', ['stream_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stream_metrics_stream_id'), table_name='stream_metrics')
    op.drop_index(op.f('ix_stream_metrics_created_at'), table_name='stream_metrics')
    op.drop_table('stream_metrics')
    op.drop_index(op.f('ix_stream_messages_stream_id'), table_name='stream_messages')
    op.drop_index(op.f('ix_stream_messages_sender_id'), table_name='stream_messages')
    op.drop_index(op.f('ix_stream_messages_created_at'), table_name='stream_messages')
    op.drop_table('stream_messages')
    op.drop_table('stream_categories')
    op.drop_index(op.f('ix_donations_stream_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_sender_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_created_at'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_clips_stream_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_creator_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_created_at'), table_name='clips')
    op.drop_table('clips')
    op.drop_index(op.f('ix_streams_created_at'), table_name='streams')
    op.drop_table('streams')
    op.drop_index(op.f('ix_followers_streamer_id'), table_name='followers')
    op.drop_index(op.f('ix_followers_follower_id'), table_name='followers')
    op.drop_index(op.f('ix_followers_created_at'), table_name='followers')
    op.drop_table('followers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
