"""update stream metric table

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-09 11:05:41.254790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream_metrics', sa.Column('total_donations', sa.Integer(), nullable=False))
    op.add_column('stream_metrics', sa.Column('donation_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream_metrics', 'donation_amount')
    op.drop_column('stream_metrics', 'total_donations')
    # ### end Alembic commands ###
