"""StreamMessage table

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-09 13:10:40.750557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_messages',
    sa.Column('stream_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_messages_created_at'), 'stream_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_stream_messages_sender_id'), 'stream_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_stream_messages_stream_id'), 'stream_messages', ['stream_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stream_messages_stream_id'), table_name='stream_messages')
    op.drop_index(op.f('ix_stream_messages_sender_id'), table_name='stream_messages')
    op.drop_index(op.f('ix_stream_messages_created_at'), table_name='stream_messages')
    op.drop_table('stream_messages')
    # ### end Alembic commands ###
